"""Static configuration for the Alpha Quant Engine.

Pure data — ticker universes, company names, regional benchmarks, theme baskets,
deep-scan lists and UI translations — extracted from app.py so the main module stays
focused on logic. No app dependencies; safe to import anywhere.
"""


# Expanded global universe. Trim any list to speed up scans (each symbol adds
# a price fetch + a fundamentals call, so ~60 tickers takes a couple of minutes).
TICKER_UNIVERSE = {
    # Ordered so the first ~10 give every THEME a representative (NVDA→AI/semis,
    # TSLA→EV/clean, LMT→defense, XOM→energy, JNJ→healthcare, JPM→financials,
    # AMZN→consumer), so a Quick scan (first N per region) still covers the Themes tab.
    "USA": ["AAPL", "MSFT", "NVDA", "AMZN", "GOOGL", "TSLA", "JPM", "LMT", "XOM", "JNJ",
            "META", "V", "WMT", "PG", "KO", "DIS", "NFLX", "AMD", "BAC", "PFE",
            "CSCO", "MRK", "HD", "RTX", "NOC", "GD", "BA", "CVX", "COP", "SLB",
            "NEE", "ENPH", "FSLR", "LLY", "UNH", "PANW", "CRWD", "ZS"],
    "Japan": ["7203.T", "6758.T", "9984.T", "6501.T", "7751.T", "4385.T",
              "8306.T", "9432.T", "6902.T", "4063.T", "8035.T",
              "7267.T", "6098.T", "9433.T", "6954.T", "8058.T"],
    "Europe": ["ASML", "MC.PA", "VOW3.DE", "SAP", "OR.PA",
               "SIE.DE", "AIR.PA", "ALV.DE", "BMW.DE", "BAS.DE",
               "SU.PA", "DTE.DE", "AI.PA", "RMS.PA"],
    "China": ["0700.HK", "9988.HK", "BABA", "JD", "BIDU",
              "1810.HK", "3690.HK", "PDD", "NIO", "2318.HK",
              "0939.HK", "1299.HK"]
}

# Plain-English company names, used by news-based sentiment sources (a ticker like
# "7203.T" never appears in an article, but "Toyota" does). Edit here to tune what
# the news scan searches for. Falls back to the ticker itself if a name is missing.
COMPANY_NAMES = {
    "AAPL": "Apple", "MSFT": "Microsoft", "NVDA": "Nvidia", "AMZN": "Amazon",
    "GOOGL": "Alphabet", "TSLA": "Tesla", "META": "Meta Platforms", "JPM": "JPMorgan",
    "V": "Visa", "WMT": "Walmart", "JNJ": "Johnson & Johnson", "PG": "Procter & Gamble",
    "XOM": "Exxon Mobil", "KO": "Coca-Cola", "DIS": "Disney", "NFLX": "Netflix",
    "AMD": "AMD", "BAC": "Bank of America", "PFE": "Pfizer", "CSCO": "Cisco",
    "MRK": "Merck", "HD": "Home Depot",
    "LMT": "Lockheed Martin", "RTX": "RTX Raytheon", "NOC": "Northrop Grumman",
    "GD": "General Dynamics", "BA": "Boeing", "CVX": "Chevron",
    "COP": "ConocoPhillips", "SLB": "SLB Schlumberger", "NEE": "NextEra Energy",
    "ENPH": "Enphase Energy", "FSLR": "First Solar", "LLY": "Eli Lilly",
    "PANW": "Palo Alto Networks", "CRWD": "CrowdStrike", "ZS": "Zscaler",
    "UNH": "UnitedHealth",
    "7203.T": "Toyota", "6758.T": "Sony", "9984.T": "SoftBank", "6501.T": "Hitachi", "4385.T": "Mercari",
    "7751.T": "Canon", "8306.T": "Mitsubishi UFJ", "9432.T": "NTT", "6902.T": "Denso",
    "4063.T": "Shin-Etsu Chemical", "8035.T": "Tokyo Electron", "7267.T": "Honda",
    "6098.T": "Recruit Holdings", "9433.T": "KDDI", "6954.T": "Fanuc", "8058.T": "Mitsubishi Corp",
    "ASML": "ASML", "MC.PA": "LVMH", "VOW3.DE": "Volkswagen", "SAP": "SAP",
    "OR.PA": "L'Oreal", "SIE.DE": "Siemens", "AIR.PA": "Airbus", "ALV.DE": "Allianz",
    "BMW.DE": "BMW", "BAS.DE": "BASF", "SU.PA": "Schneider Electric",
    "DTE.DE": "Deutsche Telekom", "AI.PA": "Air Liquide", "RMS.PA": "Hermes",
    "0700.HK": "Tencent", "9988.HK": "Alibaba", "BABA": "Alibaba", "JD": "JD.com",
    "BIDU": "Baidu", "1810.HK": "Xiaomi", "3690.HK": "Meituan", "PDD": "Pinduoduo",
    "NIO": "NIO", "2318.HK": "Ping An", "0939.HK": "China Construction Bank", "1299.HK": "AIA",
}

# Curated, cross-region theme baskets. Members are drawn from TICKER_UNIVERSE so the
# Themes tab reads straight from scan results (no extra fetching) — full coverage simply
# means running a full (non-quick) scan. A name can sit in several themes (e.g. NVDA in
# both AI and Semiconductors); that's intentional. Edit these lists to taste.
THEMES = {
    "Artificial Intelligence": ["NVDA", "MSFT", "GOOGL", "META", "AMD", "AMZN", "ASML",
                                 "8035.T", "9984.T", "BIDU"],
    "Semiconductors": ["NVDA", "AMD", "ASML", "8035.T", "4063.T"],
    "Cybersecurity": ["PANW", "CRWD", "ZS"],
    "Defense & Aerospace": ["LMT", "RTX", "NOC", "GD", "BA", "AIR.PA"],
    "Energy (Oil & Gas)": ["XOM", "CVX", "COP", "SLB"],
    "Clean Energy": ["NEE", "ENPH", "FSLR", "TSLA"],
    "EV & Mobility": ["TSLA", "NIO", "7203.T", "7267.T", "VOW3.DE", "BMW.DE"],
    "Financials": ["JPM", "V", "BAC", "8306.T", "ALV.DE", "2318.HK", "0939.HK", "1299.HK"],
    "Consumer & Luxury": ["AMZN", "WMT", "KO", "PG", "HD", "MC.PA", "OR.PA", "RMS.PA",
                          "NFLX", "DIS"],
    "China Internet": ["0700.HK", "9988.HK", "JD", "BIDU", "3690.HK", "PDD", "1810.HK"],
    # Cross-region e-commerce/marketplaces. Overlaps China Internet deliberately —
    # Alibaba is both; a Chinese finalist still routes to China Internet first (the
    # region special-case in match_theme), non-China e-commerce lands here.
    "E-Commerce & Marketplaces": ["AMZN", "JD", "PDD", "9988.HK", "3690.HK", "4385.T"],
    "Healthcare": ["JNJ", "PFE", "MRK", "LLY", "UNH"],
}

# US-only "deep scan" universe: a curated set of large, liquid US names (S&P-500-tier).
# NOT a verified exact "top-200 per exchange" ranking — it's a hand-picked large-cap list
# (knowledge cutoff Jan 2026, so very recent listing changes may be missing), editable
# like THEMES. The funnel screens ALL of these on price via one bulk download, then runs
# full fundamental scoring on only the top finalists (keeps Yahoo requests bounded).
DEEP_FINALISTS = 25

DEEP_US_TICKERS = [
    "AAPL", "MSFT", "NVDA", "GOOGL", "AMZN", "META", "AVGO", "TSLA", "ORCL", "ADBE",
    "CRM", "AMD", "INTC", "QCOM", "TXN", "CSCO", "IBM", "NOW", "INTU", "AMAT",
    "MU", "ADI", "LRCX", "KLAC", "SNPS", "CDNS", "PANW", "CRWD", "FTNT", "ZS",
    "DDOG", "SNOW", "PLTR", "WDAY", "ANET", "MRVL", "ON", "MCHP", "NXPI", "DELL",
    "NFLX", "DIS", "CMCSA", "T", "VZ", "TMUS", "EA", "TTWO", "UBER", "ABNB",
    "BKNG", "EXPE", "HD", "LOW", "MCD", "NKE", "SBUX", "TJX", "ROST", "CMG",
    "MAR", "HLT", "GM", "F", "ORLY", "AZO", "YUM", "LULU", "WMT", "PG",
    "KO", "PEP", "COST", "MDLZ", "CL", "KMB", "GIS", "KHC", "STZ", "MO",
    "PM", "KDP", "SYY", "ADM", "HSY", "KR", "JPM", "BAC", "WFC", "C",
    "GS", "MS", "SCHW", "BLK", "SPGI", "AXP", "USB", "PNC", "TFC", "COF",
    "CB", "MMC", "AON", "ICE", "CME", "MCO", "PGR", "TRV", "ALL", "MET",
    "PRU", "V", "MA", "PYPL", "FI", "UNH", "JNJ", "LLY", "ABBV", "MRK",
    "PFE", "TMO", "ABT", "DHR", "BMY", "AMGN", "CVS", "CI", "ELV", "HUM",
    "ISRG", "MDT", "SYK", "BSX", "VRTX", "REGN", "ZTS", "BDX", "MCK", "HCA",
    "BIIB", "MRNA", "GILD", "CAT", "DE", "BA", "HON", "UNP", "UPS", "RTX",
    "LMT", "GE", "MMM", "EMR", "ETN", "ITW", "GD", "NOC", "CSX", "NSC",
    "FDX", "WM", "PH", "ROP", "CARR", "OTIS", "JCI", "CMI", "PCAR", "TXT",
    "LHX", "XOM", "CVX", "COP", "SLB", "EOG", "MPC", "PSX", "VLO", "OXY",
    "WMB", "KMI", "HAL", "DVN", "HES", "BKR", "FANG", "LIN", "APD", "SHW",
    "FCX", "ECL", "NEM", "DOW", "NUE", "CTVA", "NEE", "DUK", "SO", "D",
    "AEP", "EXC", "SRE", "XEL", "ED", "PEG", "PLD", "AMT", "EQIX", "CCI",
    "PSA", "O", "SPG", "WELL", "DLR", "ENPH", "FSLR",
]

# Japan deep universe (~100 liquid TSE large/mid caps, 4-digit + .T). Curated, not a
# verified ranking; invalid/stale tickers are simply skipped by the funnel.
JP_DEEP_TICKERS = [
    "7203.T", "6758.T", "6861.T", "8035.T", "9984.T", "9983.T", "6098.T", "4063.T",
    "8306.T", "6501.T", "7974.T", "9433.T", "9432.T", "4502.T", "6902.T", "7267.T",
    "7201.T", "6594.T", "6367.T", "4519.T", "8316.T", "8411.T", "8058.T", "8001.T",
    "8031.T", "2914.T", "4661.T", "6981.T", "7741.T", "6273.T", "6954.T", "6503.T",
    "6752.T", "7751.T", "4543.T", "4568.T", "4523.T", "6857.T", "8766.T", "8801.T",
    "8802.T", "9020.T", "9022.T", "9101.T", "5108.T", "6301.T", "7011.T", "7012.T",
    "4901.T", "4452.T", "2502.T", "2503.T", "3382.T", "9201.T", "9202.T", "6645.T",
    "6701.T", "6702.T", "6724.T", "8053.T", "8002.T", "5401.T", "5411.T", "3407.T",
    "4188.T", "4005.T", "4506.T", "6326.T", "7269.T", "7270.T", "7261.T", "6471.T",
    "6479.T", "6506.T", "6770.T", "6976.T", "6963.T", "8113.T", "4911.T", "2802.T",
    "2801.T", "9613.T", "4307.T", "8604.T", "8473.T", "8630.T", "8725.T", "9434.T",
    "4385.T", "4684.T", "7182.T", "8591.T", "3659.T", "7832.T", "9602.T", "2587.T",
    "6920.T", "7733.T",
]

# China deep universe (~85). HK-weighted (####.HK) for yfinance reliability, with a few
# mainland blue chips (######.SS Shanghai / ######.SZ Shenzhen). Curated; funnel-robust.
CN_DEEP_TICKERS = [
    "0700.HK", "9988.HK", "3690.HK", "1810.HK", "9618.HK", "1024.HK", "2318.HK",
    "0939.HK", "1398.HK", "3988.HK", "0941.HK", "0883.HK", "0386.HK", "0857.HK",
    "1299.HK", "2628.HK", "0388.HK", "0005.HK", "1113.HK", "0001.HK", "0016.HK",
    "0011.HK", "2388.HK", "0688.HK", "1109.HK", "0027.HK", "1928.HK", "0066.HK",
    "0762.HK", "0728.HK", "2020.HK", "2331.HK", "6862.HK", "9999.HK", "9888.HK",
    "9626.HK", "2015.HK", "9868.HK", "1211.HK", "0175.HK", "2238.HK", "3328.HK",
    "0998.HK", "1288.HK", "6030.HK", "0291.HK", "0322.HK", "0151.HK", "2319.HK",
    "0288.HK", "1044.HK", "6618.HK", "2269.HK", "1093.HK", "1177.HK", "0241.HK",
    "3692.HK", "1801.HK", "9961.HK", "3888.HK", "9633.HK", "2382.HK", "0992.HK",
    "1772.HK", "0669.HK", "0316.HK",
    "600519.SS", "601318.SS", "600036.SS", "601166.SS", "600276.SS", "600900.SS",
    "601888.SS", "600030.SS", "000858.SZ", "000333.SZ", "000651.SZ", "002594.SZ",
    "300750.SZ", "002415.SZ", "000001.SZ", "600887.SS", "601012.SS", "600031.SS",
]

# Region -> deep universe. Europe intentionally omitted (per request).
DEEP_UNIVERSES = {"USA": DEEP_US_TICKERS, "Japan": JP_DEEP_TICKERS, "China": CN_DEEP_TICKERS}

# ---------------------------------------------------------------------------
# LIVE deep-universe refresh via Yahoo's screener (yfinance yf.screen)
# ---------------------------------------------------------------------------
# Per market: which Yahoo region codes to query, how many top-market-cap names to
# pull, how many top movers (biggest daily gainers above the cap floor) to overlay
# for discovery/churn, and the minimum market cap (USD-ish; Yahoo compares in the
# listing currency for suffixed markets, so JP/CN floors are set in local terms).
# Screener names MERGE with (never replace) the curated lists above — curation is
# the quality floor, the screener is the churn. Fully fail-safe: if the screener
# is blocked (common on cloud IPs — it's unofficial), the curated list stands.
DYNAMIC_UNIVERSE_SPEC = {
    "USA":   {"regions": ["us"],       "top_cap": 100, "movers": 25, "min_cap": 2_000_000_000},
    "Japan": {"regions": ["jp"],       "top_cap": 60,  "movers": 15, "min_cap": 300_000_000_000},
    "China": {"regions": ["hk", "cn"], "top_cap": 60,  "movers": 15, "min_cap": 20_000_000_000},
}
# Symbol suffixes accepted per market ("" = unsuffixed US listing). Anything else
# the screener returns (warrants, odd venues) is dropped.
DYNAMIC_ALLOWED_SUFFIXES = {
    "USA": {""},
    "Japan": {".T"},
    "China": {".HK", ".SS", ".SZ"},
}

# ---------------------------------------------------------------------------
# Industry/sector -> THEME classification (Deep Scan <-> Themes bridge)
# ---------------------------------------------------------------------------
# Ordered, first match wins — specific industries before catch-alls (a semiconductor
# name must land in Semiconductors, not the broad-tech AI bucket). Keys MUST match
# THEMES keys exactly. Matched against the lowercase "sector industry" string that
# yfinance/FMP return during stage-2 scoring, so this costs zero extra API calls.
# "China Internet" is special-cased in code (China region + internet keywords).
THEME_INDUSTRY_KEYWORDS = [
    ("Semiconductors",      ["semiconductor"]),
    # NOTE: Yahoo lumps most cybersecurity names into the generic industry
    # "Software - Infrastructure", so keyword classification can only catch the
    # rare explicit strings; the curated basket above is what really powers this
    # theme. PANW/CRWD/ZS deep-scan finalists will classify as AI (software) —
    # a known limit of Yahoo's taxonomy, not a map bug.
    ("Cybersecurity",       ["cyber", "security software"]),
    ("Defense & Aerospace", ["aerospace", "defense"]),
    ("Clean Energy",        ["solar", "renewable"]),
    ("Energy (Oil & Gas)",  ["oil", "gas", "coal", "uranium"]),
    ("EV & Mobility",       ["auto", "vehicle", "tire"]),
    ("Financials",          ["bank", "insurance", "capital markets", "financial",
                             "credit services", "asset management", "exchange"]),
    ("Healthcare",          ["drug", "biotech", "medical", "health", "pharma", "diagnostics"]),
    # MUST precede Consumer & Luxury: Yahoo's industry for Mercari/Amazon/Alibaba is
    # "Internet Retail", and the generic "retail" substring below would swallow it.
    # Multi-word/specific keywords always go in an earlier entry than their generic
    # substring — that's the whole ordering contract of this map.
    ("E-Commerce & Marketplaces", ["internet retail", "e-commerce", "marketplace",
                                   "online retail", "auction"]),
    ("Consumer & Luxury",   ["luxury", "apparel", "footwear", "retail", "restaurant",
                             "gaming", "entertainment",
                             "beverage", "household", "packaged food", "travel",
                             "lodging", "department store", "leisure"]),
    ("Artificial Intelligence", ["software", "information technology", "internet content",
                                 "electronic components", "communication equipment",
                                 "computer hardware", "consumer electronics", "telecom"]),
]

# ---------------------------------------------------------------------------
# Deep-scan promotions into the MAIN scan universe
# ---------------------------------------------------------------------------
# How many deep-scan winners per market may ride along with the standard
# TICKER_UNIVERSE on every main scan (US 5 / Japan 3 / China 2 = +10 max).
PROMOTION_QUOTA = {"USA": 5, "Japan": 3, "China": 2}

# The PERSISTENT layer of promoted tickers. The Deep Scan tab's "Promote" button
# writes promotions into the local SQLite DB, which Streamlit Cloud wipes on every
# restart/redeploy — so the app also shows a ready-to-paste snippet for this block.
# Paste it here in local VS Code and push to make the current promotions permanent.
# Names already in TICKER_UNIVERSE are ignored automatically (no double scanning).
PROMOTED_TICKERS = {
    "USA": [],
    "Japan": [],
    "China": [],
}

# Benchmark index per home market for the walk-forward evaluator. A pick is judged
# against the index of the exchange it actually trades on (keyed by ticker suffix),
# so a Tokyo-listed name is measured against the Nikkei rather than the S&P 500.
# Suffix-based mapping also handles dual listings correctly: a US-listed ADR with
# no suffix (e.g. BABA, ASML) is benchmarked against SPY, matching its currency and
# trading calendar. To change a mapping, edit this one dict. Anything not listed
# falls back to DEFAULT_BENCHMARK.
#
# KNOWN ASYMMETRY (accepted): stock returns are dividend-inclusive (auto_adjust=True),
# but most of these benchmarks are PRICE indices (^N225/^HSI/^FCHI/000300.SS/etc.),
# while SPY is a dividend-paying ETF (total-return when adjusted) and ^GDAXI is itself
# a total-return index. So a dividend-paying non-US/non-DE stock is judged slightly
# generously vs a price-only index. Over the 14-day EVAL_HORIZON_DAYS window the
# accrued dividend is ~0.1-0.2%, so the bias is marginal; the correct symmetric fix
# would need total-return indices in each LOCAL currency, which aren't freely
# available for JP/CN (USD ETFs like EWJ would trade this small bias for a worse
# currency mismatch), so we accept it rather than introduce that error.
BENCHMARKS = {
    "":   "SPY",        # US / NYSE / NASDAQ (no suffix)  -> S&P 500 ETF
    "T":  "^N225",      # Tokyo                           -> Nikkei 225
    "HK": "^HSI",       # Hong Kong                       -> Hang Seng
    "PA": "^FCHI",      # Paris                           -> CAC 40
    "DE": "^GDAXI",     # Frankfurt / Xetra               -> DAX
    "SS": "000300.SS",  # Shanghai (A-shares)             -> CSI 300
    "SZ": "000300.SS",  # Shenzhen (A-shares)             -> CSI 300
    "SI": "^STI",       # Singapore                       -> Straits Times
    "JK": "^JKSE",      # Jakarta                         -> IDX Composite
    "L":  "^FTSE",      # London                          -> FTSE 100
}

TRANSLATIONS = {
    "en": {
        # Sidebar
        "console_title": "🎛️ Engine Console",
        "scan_btn": "⚙️ Execute Market Analysis Scan",
        "scan_spinner": "Compiling cross-market indices...",
        "scan_success": "Global tracking array sync completed.",
        "seed_btn": "🧪 Seed Simulated Audit Dataset",
        "seed_success": "Synthetic data arrays appended to tracking engine database.",
        "skipped": "Skipped tickers: {items}",
        "scan_quick_toggle": "⚡ Quick scan (recommended on Cloud)",
        "scan_quick_help": "Scans the first 10 tickers per region (ordered so each theme gets a representative) — faster and far less likely to be rate-limited by Yahoo Finance. Untick for the full universe.",
        "all_failed": "Every fetch failed. Yahoo Finance is most likely rate-limiting this server's IP — this is common on Streamlit Cloud. Wait a few minutes and retry, or run the app locally.",
        "persistence_note": "ℹ️ On Streamlit Community Cloud, saved history is not guaranteed to persist — it resets whenever the app reboots or sleeps (after 12h idle). Use the seed button to repopulate the demo, or wire up an external database for permanent storage.",
        "benchmark_note": "📈 Accuracy is benchmark-relative: each pick counts as a win only if it beat its home market over the holding window (US→S&P 500, Japan→Nikkei 225, Hong Kong→Hang Seng, France→CAC 40, Germany→DAX).",
        # Tabs
        "tab_top": "🔥 Top Selections",
        "tab_regional": "📊 Regional Desks",
        "tab_category": "⚡ Category Screening",
        "tab_deep": "🔍 Chart Deep Dive",
        "tab_audit": "🧠 Systems Audit",
        # Engine progress
        "scanning": "Scanning Global Markets...",
        "processing": "Processing {ticker} ({region})...",
        # Top 3
        "top3_header": "🔥 Top 3 System Picks Across All Global Regions",
        "need_scan_sidebar": "Please process market metrics in the sidebar analyzer.",
        "score_suffix": "Score",
        "price_label": "Price",
        "company_profile": "Company Profile",
        "trend_return_1m": "Trend Return (1M)",
        "pe_ratio": "P/E Ratio",
        "dividend_yield": "Dividend Yield",
        # Category views
        "need_run_engine": "Run the calculations engine in the sidebar.",
        "subtab_growth": "🚀 Top Weekly Growth Selections",
        "subtab_dividend": "💰 High-Yield Dividend Picks",
        "growth_header_text": "Highest Weekly Capital Expansion Momentum",
        "dividend_header_text": "Balanced Top Recommendations with Dividends > 1.5%",
        "no_dividend_match": "No active candidates matched dividend targets in this cycle.",
        "col_ticker": "Ticker",
        "col_company": "Company",
        "col_region": "Region",
        "col_price": "Price",
        "col_momentum_1m": "1M Momentum %",
        "col_overall_score": "Overall Score",
        "col_dividend_return": "Dividend Return %",
        # Regional desks
        "need_activate": "Activate engine matrix to sort international regional distributions.",
        "select_region": "Select Geographical Workspace Focus:",
        "card_system_rating": "System Rating",
        "card_trading_close": "Trading Close",
        "card_sustained_hype": "Sustained Hype",
        "breakout": "Breakout",
        "flat": "Flat",
        # Deep dive
        "need_run_history": "Run the engine to inspect price history.",
        "select_profile": "Select Target Analytics Profile:",
        "history_workspace": "Historical Data Plot Workspace: {ticker}",
        "factor_breakdown": "Factor Breakdown",
        "why_header": "Why this pick",
        "why_composite": "Composite score",
        "why_call": "Call",
        "why_rank": "Rank in scan",
        "why_contrib_axis": "Contribution to score (points)",
        "why_contrib_caption": "Each bar is a factor's score × its weight, and the bars add up to the composite — so the longest bar is the biggest reason this name scored where it did.",
        "why_rationale": "Top drivers: {d1} ({s1}) and {d2} ({s2}) — together {share}% of the composite. Weakest area: {w} ({sw}).",
        "why_evidence": "The numbers behind each factor",
        "col_factor": "Factor",
        "col_score": "Score /100",
        "col_weight": "Weight",
        "col_contribution": "Contribution",
        "col_share": "Share",
        "col_metric": "Metric",
        "col_value": "Value",
        "price_trend": "Price & moving averages",
        "evi_ret_1m": "1-month return",
        "evi_vs_sma50": "Price vs 50-day avg",
        "evi_macd": "MACD trend",
        "evi_bullish": "bullish",
        "evi_bearish": "bearish",
        "evi_pe": "P/E ratio",
        "evi_div": "Dividend yield",
        "evi_rsi": "RSI (14)",
        "evi_bbpct": "Bollinger %B",
        "evi_roe": "Return on equity",
        "evi_mentions": "Social / news mentions",
        "evi_short": "Short interest (% float)",
        "factor_momentum": "Momentum",
        "factor_value": "Value",
        "factor_technical": "Technical",
        "factor_hype": "Hype",
        "factor_quality": "Quality",
        "wsb_mentions": "WallStreetBets Mentions",
        "wsb_caption": "Live mention count for this ticker in r/wallstreetbets hot posts during the last scan (feeds the Hype factor).",
        "wsb_source_authenticated": "🟢 Source: authenticated Reddit API (most reliable).",
        "wsb_source_rss": "🟡 Source: public RSS feed — may be blocked or throttled on cloud hosts.",
        "wsb_source_offline": "⚪ Source: offline — Reddit was unreachable, so mentions counted as 0.",
        "historical_performance": "Historical Performance (Mock Portfolio)",
        "historical_perf_note": "Return % is the live price vs. the price when the pick was logged. Green = ahead, red = behind. These curated picks also feed the walk-forward weight optimizer.",
        "audit_one_per_stock": "One row per stock (development since first pick)",
        "audit_one_per_note": "Each stock appears once. Return % is measured from its FIRST recommendation (live price vs. that price), so it shows how the call has aged. 'Times picked' = how often the engine has flagged it. Untick to see every individual pick.",
        "col_first_rec": "First recommended",
        "col_times": "Times picked",
        "no_portfolio_picks": "No saved picks yet — run a scan to start logging the mock portfolio.",
        "col_reason": "Reason",
        "col_rec_price": "Rec. Price",
        "col_current_price": "Current Price",
        "col_return_pct": "Return %",
        "reason_growth": "Top Growth",
        "reason_dividend": "Top Dividend",
        "regions_to_scan": "Regions to Scan",
        "sentiment_sources": "Sentiment Sources",
        "src_reddit": "Reddit (finance subs)",
        "src_gdelt": "Global News (GDELT)",
        "hype_buzz_label": "Social & News Buzz (mentions)",
        "hype_buzz_caption": "Combined mentions of this stock across the enabled sentiment sources during the last scan (feeds the Hype factor).",
        "hype_sources_prefix": "Buzz sources —",
        "hype_updated": "Sentiment updated {ago} ago",
        "hype_status_authenticated": "Reddit API ✓",
        "hype_status_rss": "RSS feed",
        "hype_status_ok": "live ✓",
        "hype_status_offline": "offline (0)",
        "update_hist_prices": "Update Historical Portfolio Prices",
        "no_region_selected": "Select at least one region to scan.",
        "prices_skipped": "Live price update is off — current prices and returns are left blank. Tick 'Update Historical Portfolio Prices' to refresh.",
        "prices_unavailable": "No current price came back this run for: {tickers}. This is usually Yahoo rate-limiting the request (common on shared/Cloud IPs), not bad data — wait a moment and toggle the update again.",
        "sell_privacy_note": "Your portfolio list stays in this session only — it is never saved to the database.",
        "sell_paste_label": "Paste tickers (comma, space, or newline separated)",
        "sell_upload_label": "…or upload a CSV with a 'Ticker' or 'Symbol' column",
        "sell_csv_nocol": "No 'Ticker' or 'Symbol' column found in that CSV.",
        "sell_csv_error": "Couldn't read that CSV file.",
        "sell_loaded": "{n} ticker(s) loaded: {tickers}",
        "sell_scan_btn": "Scan Portfolio",
        "sell_bulk_fetch": "Bulk-fetching price history for {total} tickers in one request…",
        "sell_scan_progress": "Scanning {done}/{total}…",
        "sell_need_portfolio": "Paste tickers or upload a CSV above, then press Scan Portfolio.",
        "sell_verdict_na": "NO DATA",
        "col_verdict": "Verdict",
        "sell_detail_expander": "🔎 View full breakdown for one ticker",
        "sell_detail_select": "Select a ticker from your scan",
        # Sell-Signal scanner
        "tab_sell": "🔻 Sell Signals",
        "tab_us": "🇺🇸 US Conviction",
        "tab_themes": "🧭 Themes",
        "themes_caption": "Industries through three lenses — Momentum (what's strong now), Attention (hype/sentiment volume), and Smart-money buys (superinvestor 13F NEW positions). Triangulate, don't predict: none forecasts the future, momentum and attention reverse, attention skews to retail-favorite megacaps, and smart-money is US-only and ~45 days lagged. Not financial advice.",
        "themes_bubble_caption": "Each bubble is a theme — right = stronger momentum, up = more attention, bigger = more superinvestor new-buys. Bottom-right (strong but quiet) can mean early institutional interest; top-left (loud but weak) is usually retail hype.",
        "themes_rank_by": "Rank themes by",
        "themes_rank_momentum": "Momentum",
        "themes_rank_hype": "Attention",
        "themes_rank_smart": "Smart-money buys",
        "themes_momentum_axis": "Avg momentum score (0–100)",
        "themes_hype_axis": "Avg attention score (0–100)",
        "themes_smart_axis": "New 13F buys (US members)",
        "themes_smart_unavailable": "Smart-money column unavailable (SEC fetch off or failed) — set SEC_USER_AGENT and rescan.",
        "themes_coverage_note": "Computed from the current scan — 'Coverage' shows how many of each theme's names were scanned (Smart-money covers all US members regardless). Untick Quick scan (and select all regions) for full coverage. Themes with nothing scanned are hidden.",
        "themes_no_coverage": "None of the theme names were in this scan. Untick Quick scan and select all regions, then rescan.",
        "themes_top_header": "Top stocks in the selected theme",
        "themes_select": "Drill into a theme",
        "col_theme": "Theme",
        "col_theme_momentum": "Momentum",
        "col_theme_hype": "Attention",
        "col_theme_smart": "Smart $ buys",
        "col_theme_strength": "Strength",
        "col_theme_ret1m": "Avg 1M %",
        "col_theme_buys": "BUYs",
        "col_theme_coverage": "Coverage",
        "col_theme_breadth": ">SMA50 %",
        "col_theme_buyspct": "BUY %",
        "col_theme_delta": "Δ Mom",
        "themes_delta_note": "Δ Mom compares average momentum with the previous recorded full scan (quick scans aren't recorded, so deltas compare like with like). History lives in the local SQLite DB — on Streamlit Cloud it resets at every redeploy, so trends accumulate meaningfully when run locally.",
        "tab_deep_scan": "🔬 Deep Scan",
        "deep_scan_intro": "Screens a curated large-cap list for the chosen market on price momentum (one bulk download), then runs full fundamental scoring on the top 25 only — so Yahoo isn't hammered. Curated large-caps, not a verified exchange ranking; not financial advice.",
        "deep_region_label": "Market",
        "deep_region_us": "🇺🇸 US (~215)",
        "deep_region_jp": "🇯🇵 Japan (~100)",
        "deep_region_cn": "🇨🇳 China (~85)",
        "deep_scan_jpcn_note": "Japan/China run on yfinance only — Stooq's free fallback is US-only, so a Yahoo throttle here can thin the screen. Lists are curated (TSE / HK-weighted) and may include stale tickers; invalid ones are skipped.",
        "deep_scan_btn": "🔬 Run deep scan",
        "deep_scan_running": "Stage 1: bulk price screen across the deep list…",
        "deep_scan_scoring": "Stage 2: full scoring on the finalists…",
        "deep_scan_hint": "Press Run deep scan to screen the large-cap list and score the top finalists. Takes a little longer than a normal scan.",
        "deep_scan_done": "Screened {screened} of {total} names on price; full-scored the top {finalists}. Ranked by composite below.",
        "deep_scan_note": "Hype is skipped on the deep scan (price + fundamentals only). A finalist that Yahoo throttled is dropped rather than shown with bad data. 'Screen score' is the stage-1 rank: 1M/3M/6M momentum (50%) + volume surge vs its 60-day average (20%) + proximity to the 52-week high (30%), with a falling-knife cap at 40 when the last month dropped more than 15%.",
        "deep_col_screen": "Screen %",
        "deep_col_score": "Screen score",
        "deep_col_dhigh": "vs 52w high",
        "deep_col_vsurge": "Vol surge",
        "deep_col_theme": "Theme",
        "dyn_refresh_btn": "🔄 Refresh universe (Yahoo screener)",
        "dyn_refresh_done": "Screener returned {n} names for this market — merged with the curated list for the next deep scan.",
        "dyn_refresh_fail": "The Yahoo screener returned nothing (it's unofficial and often blocked on cloud/shared IPs). The curated list still works as-is.",
        "dyn_universe_status": "Deep universe: {curated} curated + {dynamic} live from the screener (top market cap + biggest movers){ago}",
        "themes_deep_echo": "🔭 Deep-scan echo — finalists matching these themes",
        "themes_deep_echo_note": "The latest deep-scan finalists (any market), classified into these theme baskets by their Yahoo sector/industry — top 3 per theme by composite. Names outside the curated baskets can surface here, which is the point: theme heat confirmed (or contradicted) by the wider market.",
        "themes_deep_echo_none": "No deep-scan finalist matched a theme basket.",
        "themes_deep_echo_hint": "Tip: run a Deep Scan and its finalists will be cross-referenced against these themes here.",
        "promote_btn": "⭐ Promote top {n} into the main scan",
        "promote_done": "Promoted {added} name(s) into the main scan universe. {skipped} of the top finalists were already in it.",
        "promote_none": "No new names to promote — the top finalists are already in the main universe.",
        "promoted_current": "⭐ Riding along with every main scan: {items}",
        "promote_clear": "Clear promotions",
        "promote_clear_note": "Cleared the promotions saved in the app database. Any names hard-coded in config.py's PROMOTED_TICKERS stay until you edit the file.",
        "promote_snippet_hint": "Streamlit Cloud wipes the app's database on every restart/redeploy, so promotions made here are temporary. To make them permanent, paste this block over PROMOTED_TICKERS in config.py (local VS Code) and push:",
        "promoted_sidebar": "incl. {n} promoted deep-scan name(s)",
        "us_spinner": "Pulling audited SEC EDGAR fundamentals…",
        "us_module_missing": "The sec_research.py companion module isn't available — place it beside app.py.",
        "us_conviction_suffix": "conviction",
        "us_caption": "US-listed names only, ranked by a blend of your scan composite (50%) with SEC EDGAR growth (30%) and quality (20%) from audited multi-year filings, plus a capped bonus for NEW 13F buys. Isolated from the global factor weights and walk-forward loop. 13F overlay = positions newly added quarter-over-quarter (latest vs prior 13F-HR, ~45-day lag), matched by company name across 7 tracked managers — so long-standing mega-cap holdings don't score. Set SEC_USER_AGENT (your email) per SEC's fair-access policy.",
        "col_us_conviction": "US Conviction",
        "col_sec_growth": "SEC Growth",
        "col_sec_quality": "SEC Quality",
        "col_rev_cagr": "3y Rev CAGR %",
        "col_eps_yoy": "EPS YoY %",
        "col_superinvestors": "New 13F Buys",
        "us_held_by": "Newly bought by {n} superinvestor(s)",
        "sell_header": "🔻 Sell-Signal Scanner",
        "sell_disclaimer": "Informational signals only — not financial advice. Data via Yahoo Finance; analyst and insider coverage is richest for US-listed symbols.",
        "sell_input_label": "Enter a ticker symbol",
        "sell_btn": "Analyze",
        "sell_spinner": "Scanning sell signals for {ticker}...",
        "sell_need_input": "Type a ticker symbol above (e.g. AAPL, MSFT, ABBV) to scan for sell signals.",
        "sell_no_data": "Couldn't retrieve price data for '{ticker}'. Check the symbol — for the richest analyst and insider data, try the US listing (e.g. ABBV instead of 4AB, MSFT instead of MSF).",
        "sell_pressure": "Sell Pressure",
        "sell_verdict_high": "ELEVATED",
        "sell_verdict_mixed": "MIXED",
        "sell_verdict_low": "LOW",
        "sell_breakdown_title": "Signal Breakdown (higher = more bearish)",
        "sell_why_header": "Why this is a sell",
        "sell_why_axis": "Contribution to sell-pressure (points)",
        "sell_why_caption": "Each bar is a bearish signal's score × its weight (over the signals that had data), and the bars sum to the sell-pressure score — so the longest bar is the biggest red flag.",
        "sell_why_rationale": "Biggest red flags: {d1} ({s1}) and {d2} ({s2}) — together {share}% of the sell-pressure score.",
        "sell_why_rationale_one": "Main red flag: {d1} ({s1}) — {share}% of the sell-pressure score.",
        "sell_not_scored": "Not scored (no data): {items}.",
        "sell_no_signal_data": "No bearish signals returned data for this ticker, so there's no sell-pressure score to explain.",
        "sell_recent_downgrades": "Recent Analyst Rating Changes",
        "sell_insider_activity": "Recent Insider Transactions",
        "sell_no_analyst": "No recent analyst rating changes available for this symbol.",
        "sell_no_insider": "No insider transactions reported for this symbol.",
        "kpi_analyst": "Analyst Consensus",
        "kpi_downgrades": "Rating Changes",
        "kpi_target": "Price-Target Downside",
        "kpi_insider": "Insider Selling",
        "kpi_technical": "Technical Breakdown",
        "kpi_momentum": "Momentum Trend",
        "kpi_short": "Short Interest",
        "col_kpi": "Indicator",
        "col_signal": "Signal (0-100)",
        "col_reading": "Reading",
        "col_date": "Date",
        "col_firm": "Firm",
        "col_from": "From",
        "col_to": "To",
        "col_action": "Action",
        "col_insider": "Insider",
        "col_transaction": "Transaction",
        "col_shares": "Shares",
        "col_value": "Value",
        # Audit
        "audit_header_text": "🧠 Machine Weight Analytics & Historical Integrity",
        "no_tracks": "No calculation tracks logged yet.",
        "card_archived_calls": "Archived Calls",
        "card_perf_verified": "Performance Verified",
        "card_accuracy": "Historical Accuracy Score",
        "winrate_over_time": "Win rate over time",
        "winrate_col": "Win Rate %",
        "kpi_weight_evolution": "KPI weight evolution",
        # Recommendation pills
        "rec_BUY": "BUY",
        "rec_HOLD": "HOLD",
        "rec_SELL": "SELL",
    },
    "ja": {
        # サイドバー
        "console_title": "🎛️ エンジンコンソール",
        "scan_btn": "⚙️ 市場分析スキャンを実行",
        "scan_spinner": "市場横断インデックスを集計中...",
        "scan_success": "グローバル追跡データの同期が完了しました。",
        "seed_btn": "🧪 監査用サンプルデータを生成",
        "seed_success": "サンプルデータをトラッキングDBに追加しました。",
        "skipped": "スキップした銘柄: {items}",
        "scan_quick_toggle": "⚡ クイックスキャン（クラウド推奨）",
        "scan_quick_help": "各地域の先頭10銘柄をスキャンします（各テーマの代表が含まれるよう並び替え済み）。高速でレート制限にかかりにくくなります。全銘柄はチェックを外してください。",
        "all_failed": "すべての取得に失敗しました。Yahoo Finance がこのサーバーのIPをレート制限している可能性が高いです（Streamlit Cloud ではよくあります）。数分待って再試行するか、ローカルで実行してください。",
        "persistence_note": "ℹ️ Streamlit Community Cloud では、保存された履歴は永続化が保証されません。アプリの再起動やスリープ（12時間無操作）のたびにリセットされます。シードボタンでデモを再生成するか、外部データベースを接続して永続保存してください。",
        "benchmark_note": "📈 的中率はベンチマーク相対です。各推奨は保有期間中に自国市場を上回った場合のみ「勝ち」と判定されます（米国→S&P500、日本→日経225、香港→ハンセン、フランス→CAC40、ドイツ→DAX）。",
        # タブ
        "tab_top": "🔥 トップ銘柄",
        "tab_regional": "📊 地域別デスク",
        "tab_category": "⚡ カテゴリ別スクリーニング",
        "tab_deep": "🔍 チャート詳細分析",
        "tab_audit": "🧠 システム監査",
        # 進捗
        "scanning": "グローバル市場をスキャン中...",
        "processing": "{ticker}（{region}）を処理中...",
        # トップ3
        "top3_header": "🔥 全地域から選んだトップ3銘柄",
        "need_scan_sidebar": "サイドバーのアナライザーで市場データを処理してください。",
        "score_suffix": "スコア",
        "price_label": "価格",
        "company_profile": "企業プロフィール",
        "trend_return_1m": "トレンドリターン（1ヶ月）",
        "pe_ratio": "PER（株価収益率）",
        "dividend_yield": "配当利回り",
        # カテゴリ別
        "need_run_engine": "サイドバーで計算エンジンを実行してください。",
        "subtab_growth": "🚀 週間グロース上位銘柄",
        "subtab_dividend": "💰 高配当銘柄",
        "growth_header_text": "週間モメンタム上位銘柄",
        "dividend_header_text": "配当利回り1.5%超のおすすめ銘柄",
        "no_dividend_match": "今回のサイクルでは配当条件に合う銘柄がありませんでした。",
        "col_ticker": "銘柄",
        "col_company": "会社名",
        "col_region": "地域",
        "col_price": "価格",
        "col_momentum_1m": "1ヶ月モメンタム %",
        "col_overall_score": "総合スコア",
        "col_dividend_return": "配当利回り %",
        # 地域別デスク
        "need_activate": "エンジンを実行して地域別の分布を表示してください。",
        "select_region": "対象地域を選択:",
        "card_system_rating": "システム評価",
        "card_trading_close": "終値",
        "card_sustained_hype": "継続的な注目度",
        "breakout": "急騰",
        "flat": "横ばい",
        # 詳細分析
        "need_run_history": "エンジンを実行すると価格履歴を確認できます。",
        "select_profile": "分析する銘柄を選択:",
        "history_workspace": "価格履歴チャート: {ticker}",
        "factor_breakdown": "ファクター内訳",
        "why_header": "選定理由",
        "why_composite": "総合スコア",
        "why_call": "判定",
        "why_rank": "スキャン内順位",
        "why_contrib_axis": "スコアへの寄与（ポイント）",
        "why_contrib_caption": "各バーはファクターのスコア×ウェイトで、合計が総合スコアになります。最も長いバーが、この銘柄のスコアを最も押し上げた理由です。",
        "why_rationale": "主な要因：{d1}（{s1}）と{d2}（{s2}）で総合スコアの{share}%。最も弱い項目：{w}（{sw}）。",
        "why_evidence": "各ファクターの根拠となる数値",
        "col_factor": "ファクター",
        "col_score": "スコア /100",
        "col_weight": "ウェイト",
        "col_contribution": "寄与",
        "col_share": "占有率",
        "col_metric": "指標",
        "col_value": "値",
        "price_trend": "株価と移動平均",
        "evi_ret_1m": "1か月リターン",
        "evi_vs_sma50": "株価 対 50日平均",
        "evi_macd": "MACDトレンド",
        "evi_bullish": "強気",
        "evi_bearish": "弱気",
        "evi_pe": "PER（株価収益率）",
        "evi_div": "配当利回り",
        "evi_rsi": "RSI（14）",
        "evi_bbpct": "ボリンジャー%B",
        "evi_roe": "ROE（自己資本利益率）",
        "evi_mentions": "SNS・ニュース言及数",
        "evi_short": "空売り比率（浮動株%）",
        "factor_momentum": "モメンタム",
        "factor_value": "バリュー",
        "factor_technical": "テクニカル",
        "factor_hype": "ハイプ",
        "factor_quality": "クオリティ",
        "wsb_mentions": "WallStreetBets 言及数",
        "wsb_caption": "直近のスキャン時に r/wallstreetbets の人気投稿でこの銘柄が言及された回数（ハイプ・ファクターに反映されます）。",
        "wsb_source_authenticated": "🟢 ソース：認証済み Reddit API（最も安定）。",
        "wsb_source_rss": "🟡 ソース：公開RSSフィード（クラウド環境ではブロック・制限される場合があります）。",
        "wsb_source_offline": "⚪ ソース：オフライン（Redditに接続できず、言及数は0としてカウント）。",
        "historical_performance": "ヒストリカル・パフォーマンス（模擬ポートフォリオ）",
        "historical_perf_note": "リターン％は、記録時の株価に対する現在株価の変化です。緑＝プラス、赤＝マイナス。これらの厳選銘柄はウォークフォワード重み最適化にも反映されます。",
        "audit_one_per_stock": "銘柄ごとに1行（初回推奨からの推移）",
        "audit_one_per_note": "各銘柄は1回のみ表示。リターン％は初回推奨時の株価を基準に算出（現在株価との比較）し、推奨の経過を示します。「推奨回数」はエンジンが選出した回数です。チェックを外すと個別の推奨をすべて表示します。",
        "col_first_rec": "初回推奨日",
        "col_times": "推奨回数",
        "no_portfolio_picks": "保存された推奨はまだありません。スキャンを実行すると模擬ポートフォリオの記録が始まります。",
        "col_reason": "理由",
        "col_rec_price": "推奨時株価",
        "col_current_price": "現在株価",
        "col_return_pct": "リターン %",
        "reason_growth": "成長株トップ",
        "reason_dividend": "高配当トップ",
        "regions_to_scan": "スキャンする地域",
        "sentiment_sources": "センチメント・ソース",
        "src_reddit": "Reddit（金融系サブレディット）",
        "src_gdelt": "グローバルニュース（GDELT）",
        "hype_buzz_label": "ソーシャル・ニュース言及数",
        "hype_buzz_caption": "直近のスキャン時に、有効化したセンチメント・ソース全体でこの銘柄が言及された合計回数（ハイプ・ファクターに反映されます）。",
        "hype_sources_prefix": "バズの取得元 —",
        "hype_updated": "センチメント更新：{ago}前",
        "hype_status_authenticated": "Reddit API ✓",
        "hype_status_rss": "RSSフィード",
        "hype_status_ok": "ライブ ✓",
        "hype_status_offline": "オフライン (0)",
        "update_hist_prices": "履歴ポートフォリオの株価を更新",
        "no_region_selected": "スキャンする地域を1つ以上選択してください。",
        "prices_skipped": "ライブ株価の更新はオフです。現在株価とリターンは空欄です。「履歴ポートフォリオの株価を更新」をオンにすると更新されます。",
        "prices_unavailable": "今回の更新で現在株価を取得できませんでした：{tickers}。これは通常、データ不良ではなくYahoo側のレート制限（共有IPやクラウドで発生しやすい）です。少し待ってから更新を再実行してください。",
        "sell_privacy_note": "ポートフォリオのリストはこのセッション内にのみ保持され、データベースには保存されません。",
        "sell_paste_label": "ティッカーを貼り付け（カンマ・スペース・改行区切り）",
        "sell_upload_label": "…または「Ticker」「Symbol」列を含むCSVをアップロード",
        "sell_csv_nocol": "そのCSVに「Ticker」または「Symbol」列が見つかりませんでした。",
        "sell_csv_error": "そのCSVファイルを読み込めませんでした。",
        "sell_loaded": "{n} 銘柄を読み込みました：{tickers}",
        "sell_scan_btn": "ポートフォリオをスキャン",
        "sell_bulk_fetch": "{total} 銘柄の価格履歴を一括取得中…",
        "sell_scan_progress": "スキャン中 {done}/{total}…",
        "sell_need_portfolio": "上にティッカーを貼り付けるかCSVをアップロードし、「ポートフォリオをスキャン」を押してください。",
        "sell_verdict_na": "データなし",
        "col_verdict": "判定",
        "sell_detail_expander": "🔎 個別銘柄の詳細を表示",
        "sell_detail_select": "スキャンした銘柄から選択",
        # 売りシグナル・スキャナー
        "tab_sell": "🔻 売りシグナル",
        "tab_us": "🇺🇸 米国確信度",
        "tab_themes": "🧭 テーマ",
        "themes_caption": "業界を3つの視点で見ます — モメンタム（今の強さ）、注目度（ハイプ/言及量）、スマートマネー買い（著名投資家の13F新規ポジション）。予測ではなく多角的な確認に使ってください：いずれも将来を予測するものではなく、モメンタムと注目度は反転し、注目度は個人投資家好みの大型株に偏り、スマートマネーは米国のみ・約45日遅延です。投資助言ではありません。",
        "themes_bubble_caption": "各バブルがテーマです — 右ほどモメンタムが強く、上ほど注目度が高く、大きいほど著名投資家の新規買いが多いことを示します。右下（強いが静か）は機関投資家の初期関心の可能性、左上（騒がしいが弱い）は個人の過熱を示すことが多いです。",
        "themes_rank_by": "並び替え基準",
        "themes_rank_momentum": "モメンタム",
        "themes_rank_hype": "注目度",
        "themes_rank_smart": "スマートマネー買い",
        "themes_momentum_axis": "平均モメンタムスコア（0〜100）",
        "themes_hype_axis": "平均注目度スコア（0〜100）",
        "themes_smart_axis": "13F新規買い（米国銘柄）",
        "themes_smart_unavailable": "スマートマネー列は利用できません（SEC取得がオフまたは失敗）。SEC_USER_AGENT を設定して再スキャンしてください。",
        "themes_coverage_note": "現在のスキャン結果から算出。「カバレッジ」は各テーマの銘柄のうちスキャン済みの数です（スマートマネーは全米国銘柄を対象）。完全なカバレッジにはクイックスキャンを外し全地域を選択してください。スキャンされた銘柄がないテーマは非表示です。",
        "themes_no_coverage": "今回のスキャンにテーマ銘柄が含まれていません。クイックスキャンを外し全地域を選択して再スキャンしてください。",
        "themes_top_header": "選択テーマの上位銘柄",
        "themes_select": "テーマを掘り下げる",
        "col_theme": "テーマ",
        "col_theme_momentum": "モメンタム",
        "col_theme_hype": "注目度",
        "col_theme_smart": "スマート買い",
        "col_theme_strength": "総合力",
        "col_theme_ret1m": "平均1か月%",
        "col_theme_buys": "BUY数",
        "col_theme_coverage": "カバレッジ",
        "col_theme_breadth": ">SMA50 %",
        "col_theme_buyspct": "BUY %",
        "col_theme_delta": "Δモメンタム",
        "themes_delta_note": "Δモメンタムは前回記録されたフルスキャンとの平均モメンタム比較です（クイックスキャンは記録されないため、同条件同士の比較になります）。履歴はローカルのSQLite DBに保存され、Streamlit Cloudでは再デプロイごとにリセットされます。ローカル実行でこそトレンドが蓄積されます。",
        "tab_deep_scan": "🔬 ディープスキャン",
        "deep_scan_intro": "選択した市場の厳選大型株リストを価格モメンタムでスクリーニングし（一括ダウンロード）、上位25銘柄のみ完全なファンダメンタル評価を行います。Yahooへの負荷を抑えるためです。検証済みの取引所ランキングではなく厳選した大型株です。投資助言ではありません。",
        "deep_region_label": "市場",
        "deep_region_us": "🇺🇸 米国（約215）",
        "deep_region_jp": "🇯🇵 日本（約100）",
        "deep_region_cn": "🇨🇳 中国（約85）",
        "deep_scan_jpcn_note": "日本・中国はyfinanceのみで動作します（Stooqの無料フォールバックは米国専用）。そのためレート制限を受けると対象が減ることがあります。リストは厳選（東証・香港中心）で古い銘柄を含む可能性があり、無効な銘柄はスキップされます。",
        "deep_scan_btn": "🔬 ディープスキャン実行",
        "deep_scan_running": "ステージ1：ディープリストの一括価格スクリーニング…",
        "deep_scan_scoring": "ステージ2：ファイナリストの完全評価…",
        "deep_scan_hint": "「ディープスキャン実行」を押すと大型株リストをスクリーニングし上位銘柄を評価します。通常スキャンより少し時間がかかります。",
        "deep_scan_done": "{total}銘柄中{screened}銘柄を価格でスクリーニングし、上位{finalists}銘柄を完全評価しました。以下は総合スコア順です。",
        "deep_scan_note": "ディープスキャンではハイプを除外します（価格＋ファンダメンタルのみ）。Yahooのレート制限を受けたファイナリストは誤データを表示せず除外します。「スクリーンスコア」は第1段階のランク: 1か月/3か月/6か月モメンタム（50%）＋60日平均比の出来高急増（20%）＋52週高値への近さ（30%）。直近1か月で15%超下落した銘柄は40点で頭打ち（落ちるナイフ対策）。",
        "deep_col_screen": "スクリーン%",
        "deep_col_score": "スクリーンスコア",
        "deep_col_dhigh": "52週高値比",
        "deep_col_vsurge": "出来高急増",
        "deep_col_theme": "テーマ",
        "dyn_refresh_btn": "🔄 ユニバースを更新（Yahooスクリーナー）",
        "dyn_refresh_done": "スクリーナーがこの市場で{n}銘柄を返しました — 次回のディープスキャンでキュレーション済みリストと統合されます。",
        "dyn_refresh_fail": "Yahooスクリーナーが応答しませんでした（非公式APIのため、クラウド/共有IPではブロックされがちです）。キュレーション済みリストはそのまま使えます。",
        "dyn_universe_status": "ディープユニバース: キュレーション{curated}銘柄＋スクリーナー{dynamic}銘柄（時価総額上位＋値上がり上位）{ago}",
        "themes_deep_echo": "🔭 ディープスキャン・エコー — テーマに合致したファイナリスト",
        "themes_deep_echo_note": "最新のディープスキャンのファイナリスト（全市場）を、Yahooのセクター/業種でテーマバスケットに分類 — テーマごとに総合スコア上位3銘柄。キュレーション外の銘柄もここに現れます。それが狙いです: テーマの過熱を市場全体で裏付け（または反証）します。",
        "themes_deep_echo_none": "テーマバスケットに合致するディープスキャンのファイナリストはありませんでした。",
        "themes_deep_echo_hint": "ヒント: ディープスキャンを実行すると、そのファイナリストがここでテーマと照合されます。",
        "promote_btn": "⭐ 上位{n}銘柄をメインスキャンに昇格",
        "promote_done": "{added}銘柄をメインスキャンのユニバースに昇格しました。上位ファイナリストのうち{skipped}銘柄は既に含まれていました。",
        "promote_none": "昇格できる新規銘柄はありません — 上位ファイナリストは既にメインユニバースに含まれています。",
        "promoted_current": "⭐ 毎回のメインスキャンに同乗中: {items}",
        "promote_clear": "昇格をクリア",
        "promote_clear_note": "アプリのデータベースに保存された昇格をクリアしました。config.py の PROMOTED_TICKERS にハードコードされた銘柄はファイルを編集するまで残ります。",
        "promote_snippet_hint": "Streamlit Cloud は再起動・再デプロイのたびにアプリのデータベースを消去するため、ここでの昇格は一時的です。恒久化するには、このブロックをローカルの VS Code で config.py の PROMOTED_TICKERS に貼り付けてプッシュしてください:",
        "promoted_sidebar": "うち{n}銘柄はディープスキャンからの昇格",
        "us_spinner": "SECの監査済み財務データ（EDGAR）を取得中…",
        "us_module_missing": "コンパニオンモジュール sec_research.py がありません。app.py と同じフォルダに置いてください。",
        "us_conviction_suffix": "確信度",
        "us_caption": "米国上場銘柄のみ。スキャンの総合スコア（50%）に、SEC EDGARの監査済み複数年財務に基づく成長性（30%）と品質（20%）、さらに13Fの新規買いに対する上限付きボーナスを加味してランク付けします。グローバルの重みやウォークフォワード学習からは分離されています。13Fは前四半期比で新規に追加された銘柄（最新と前回の13F-HRの差分、約45日遅延）を7名の著名投資家について会社名でマッチング。長期保有の大型株は加点されません。SECのフェアアクセス方針に従い SEC_USER_AGENT（メールアドレス）を設定してください。",
        "col_us_conviction": "米国確信度",
        "col_sec_growth": "SEC成長性",
        "col_sec_quality": "SEC品質",
        "col_rev_cagr": "売上CAGR(3年)%",
        "col_eps_yoy": "EPS前年比%",
        "col_superinvestors": "新規買い(13F)",
        "us_held_by": "{n}名の著名投資家が新規購入",
        "sell_header": "🔻 売りシグナル・スキャナー",
        "sell_disclaimer": "本機能は情報提供のみを目的とし、投資助言ではありません。データはYahoo Finance提供。アナリスト・インサイダー情報は米国上場銘柄が最も充実しています。",
        "sell_input_label": "ティッカーシンボルを入力",
        "sell_btn": "分析",
        "sell_spinner": "{ticker} の売りシグナルを分析中...",
        "sell_need_input": "上の欄にティッカー（例：AAPL、MSFT、ABBV）を入力すると売りシグナルを分析します。",
        "sell_no_data": "'{ticker}' の価格データを取得できませんでした。シンボルをご確認ください。アナリスト・インサイダー情報を充実させるには米国上場銘柄（例：4AB→ABBV、MSF→MSFT）をお試しください。",
        "sell_pressure": "売り圧力",
        "sell_verdict_high": "強い",
        "sell_verdict_mixed": "中程度",
        "sell_verdict_low": "弱い",
        "sell_breakdown_title": "シグナル内訳（高いほど弱気）",
        "sell_why_header": "売却シグナルの理由",
        "sell_why_axis": "売り圧力への寄与（ポイント）",
        "sell_why_caption": "各バーは弱気シグナルのスコア×ウェイト（データのあるシグナルのみ）で、合計が売り圧力スコアになります。最も長いバーが最大の懸念材料です。",
        "sell_why_rationale": "主な懸念材料：{d1}（{s1}）と{d2}（{s2}）で売り圧力スコアの{share}%。",
        "sell_why_rationale_one": "主な懸念材料：{d1}（{s1}）— 売り圧力スコアの{share}%。",
        "sell_not_scored": "データなしで未評価：{items}。",
        "sell_no_signal_data": "この銘柄では弱気シグナルのデータが得られず、説明できる売り圧力スコアがありません。",
        "sell_recent_downgrades": "最近のアナリスト格付け変更",
        "sell_insider_activity": "最近のインサイダー取引",
        "sell_no_analyst": "この銘柄の最近のアナリスト格付け変更はありません。",
        "sell_no_insider": "この銘柄のインサイダー取引は報告されていません。",
        "kpi_analyst": "アナリスト・コンセンサス",
        "kpi_downgrades": "格付け変更",
        "kpi_target": "目標株価との乖離",
        "kpi_insider": "インサイダー売却",
        "kpi_technical": "テクニカルの崩れ",
        "kpi_momentum": "モメンタム動向",
        "kpi_short": "空売り比率",
        "col_kpi": "指標",
        "col_signal": "シグナル (0-100)",
        "col_reading": "内容",
        "col_date": "日付",
        "col_firm": "証券会社",
        "col_from": "変更前",
        "col_to": "変更後",
        "col_action": "アクション",
        "col_insider": "インサイダー",
        "col_transaction": "取引",
        "col_shares": "株数",
        "col_value": "金額",
        # 監査
        "audit_header_text": "🧠 重み学習の分析と過去実績",
        "no_tracks": "まだ記録された計算履歴はありません。",
        "card_archived_calls": "記録された判定",
        "card_perf_verified": "結果検証済み",
        "card_accuracy": "過去の的中率",
        "winrate_over_time": "勝率の推移",
        "winrate_col": "勝率 %",
        "kpi_weight_evolution": "重み（KPI）の推移",
        # 推奨ピル
        "rec_BUY": "買い",
        "rec_HOLD": "中立",
        "rec_SELL": "売り",
    },
}
